INCLUDEPATH += c_library_v2

HEADERS  +=c_library_v2/checksum.h \
    c_library_v2/mavlink_conversions.h \
    c_library_v2/mavlink_get_info.h \
    c_library_v2/mavlink_helpers.h \
    c_library_v2/mavlink_sha256.h \
    c_library_v2/mavlink_types.h \
    c_library_v2/protocol.h \
    c_library_v2/ardupilotmega/ardupilotmega.h \
    c_library_v2/ardupilotmega/mavlink.h \
    c_library_v2/ardupilotmega/mavlink_msg_adap_tuning.h \
    c_library_v2/ardupilotmega/mavlink_msg_ahrs.h \
    c_library_v2/ardupilotmega/mavlink_msg_ahrs2.h \
    c_library_v2/ardupilotmega/mavlink_msg_ahrs3.h \
    c_library_v2/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    c_library_v2/ardupilotmega/mavlink_msg_aoa_ssa.h \
    c_library_v2/ardupilotmega/mavlink_msg_ap_adc.h \
    c_library_v2/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    c_library_v2/ardupilotmega/mavlink_msg_battery2.h \
    c_library_v2/ardupilotmega/mavlink_msg_camera_feedback.h \
    c_library_v2/ardupilotmega/mavlink_msg_camera_status.h \
    c_library_v2/ardupilotmega/mavlink_msg_compassmot_status.h \
    c_library_v2/ardupilotmega/mavlink_msg_data16.h \
    c_library_v2/ardupilotmega/mavlink_msg_data32.h \
    c_library_v2/ardupilotmega/mavlink_msg_data64.h \
    c_library_v2/ardupilotmega/mavlink_msg_data96.h \
    c_library_v2/ardupilotmega/mavlink_msg_deepstall.h \
    c_library_v2/ardupilotmega/mavlink_msg_device_op_read.h \
    c_library_v2/ardupilotmega/mavlink_msg_device_op_read_reply.h \
    c_library_v2/ardupilotmega/mavlink_msg_device_op_write.h \
    c_library_v2/ardupilotmega/mavlink_msg_device_op_write_reply.h \
    c_library_v2/ardupilotmega/mavlink_msg_digicam_configure.h \
    c_library_v2/ardupilotmega/mavlink_msg_digicam_control.h \
    c_library_v2/ardupilotmega/mavlink_msg_ekf_status_report.h \
    c_library_v2/ardupilotmega/mavlink_msg_esc_telemetry_1_to_4.h \
    c_library_v2/ardupilotmega/mavlink_msg_esc_telemetry_5_to_8.h \
    c_library_v2/ardupilotmega/mavlink_msg_esc_telemetry_9_to_12.h \
    c_library_v2/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    c_library_v2/ardupilotmega/mavlink_msg_fence_point.h \
    c_library_v2/ardupilotmega/mavlink_msg_gimbal_control.h \
    c_library_v2/ardupilotmega/mavlink_msg_gimbal_report.h \
    c_library_v2/ardupilotmega/mavlink_msg_gimbal_torque_cmd_report.h \
    c_library_v2/ardupilotmega/mavlink_msg_gopro_get_request.h \
    c_library_v2/ardupilotmega/mavlink_msg_gopro_get_response.h \
    c_library_v2/ardupilotmega/mavlink_msg_gopro_heartbeat.h \
    c_library_v2/ardupilotmega/mavlink_msg_gopro_set_request.h \
    c_library_v2/ardupilotmega/mavlink_msg_gopro_set_response.h \
    c_library_v2/ardupilotmega/mavlink_msg_hwstatus.h \
    c_library_v2/ardupilotmega/mavlink_msg_led_control.h \
    c_library_v2/ardupilotmega/mavlink_msg_limits_status.h \
    c_library_v2/ardupilotmega/mavlink_msg_mag_cal_progress.h \
    c_library_v2/ardupilotmega/mavlink_msg_mag_cal_report.h \
    c_library_v2/ardupilotmega/mavlink_msg_meminfo.h \
    c_library_v2/ardupilotmega/mavlink_msg_mount_configure.h \
    c_library_v2/ardupilotmega/mavlink_msg_mount_control.h \
    c_library_v2/ardupilotmega/mavlink_msg_mount_status.h \
    c_library_v2/ardupilotmega/mavlink_msg_pid_tuning.h \
    c_library_v2/ardupilotmega/mavlink_msg_radio.h \
    c_library_v2/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    c_library_v2/ardupilotmega/mavlink_msg_rally_point.h \
    c_library_v2/ardupilotmega/mavlink_msg_rangefinder.h \
    c_library_v2/ardupilotmega/mavlink_msg_remote_log_block_status.h \
    c_library_v2/ardupilotmega/mavlink_msg_remote_log_data_block.h \
    c_library_v2/ardupilotmega/mavlink_msg_rpm.h \
    c_library_v2/ardupilotmega/mavlink_msg_sensor_offsets.h \
    c_library_v2/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    c_library_v2/ardupilotmega/mavlink_msg_simstate.h \
    c_library_v2/ardupilotmega/mavlink_msg_vision_position_delta.h \
    c_library_v2/ardupilotmega/mavlink_msg_wind.h \
    c_library_v2/ardupilotmega/testsuite.h \
    c_library_v2/ardupilotmega/version.h \
    c_library_v2/ASLUAV/ASLUAV.h \
    c_library_v2/ASLUAV/mavlink.h \
    c_library_v2/ASLUAV/mavlink_msg_asl_obctrl.h \
    c_library_v2/ASLUAV/mavlink_msg_aslctrl_data.h \
    c_library_v2/ASLUAV/mavlink_msg_aslctrl_debug.h \
    c_library_v2/ASLUAV/mavlink_msg_asluav_status.h \
    c_library_v2/ASLUAV/mavlink_msg_command_int_stamped.h \
    c_library_v2/ASLUAV/mavlink_msg_command_long_stamped.h \
    c_library_v2/ASLUAV/mavlink_msg_ekf_ext.h \
    c_library_v2/ASLUAV/mavlink_msg_fw_soaring_data.h \
    c_library_v2/ASLUAV/mavlink_msg_gsm_link_status.h \
    c_library_v2/ASLUAV/mavlink_msg_sens_atmos.h \
    c_library_v2/ASLUAV/mavlink_msg_sens_batmon.h \
    c_library_v2/ASLUAV/mavlink_msg_sens_mppt.h \
    c_library_v2/ASLUAV/mavlink_msg_sens_power.h \
    c_library_v2/ASLUAV/mavlink_msg_sens_power_board.h \
    c_library_v2/ASLUAV/mavlink_msg_sensorpod_status.h \
    c_library_v2/ASLUAV/testsuite.h \
    c_library_v2/ASLUAV/version.h \
    c_library_v2/autoquad/autoquad.h \
    c_library_v2/autoquad/mavlink.h \
    c_library_v2/autoquad/mavlink_msg_aq_esc_telemetry.h \
    c_library_v2/autoquad/mavlink_msg_aq_telemetry_f.h \
    c_library_v2/autoquad/testsuite.h \
    c_library_v2/autoquad/version.h \
    c_library_v2/common/common.h \
    c_library_v2/common/mavlink.h \
    c_library_v2/common/mavlink_msg_actuator_control_target.h \
    c_library_v2/common/mavlink_msg_actuator_output_status.h \
    c_library_v2/common/mavlink_msg_adsb_vehicle.h \
    c_library_v2/common/mavlink_msg_altitude.h \
    c_library_v2/common/mavlink_msg_att_pos_mocap.h \
    c_library_v2/common/mavlink_msg_attitude.h \
    c_library_v2/common/mavlink_msg_attitude_quaternion.h \
    c_library_v2/common/mavlink_msg_attitude_quaternion_cov.h \
    c_library_v2/common/mavlink_msg_attitude_target.h \
    c_library_v2/common/mavlink_msg_auth_key.h \
    c_library_v2/common/mavlink_msg_autopilot_version.h \
    c_library_v2/common/mavlink_msg_battery_status.h \
    c_library_v2/common/mavlink_msg_button_change.h \
    c_library_v2/common/mavlink_msg_camera_capture_status.h \
    c_library_v2/common/mavlink_msg_camera_image_captured.h \
    c_library_v2/common/mavlink_msg_camera_information.h \
    c_library_v2/common/mavlink_msg_camera_settings.h \
    c_library_v2/common/mavlink_msg_camera_trigger.h \
    c_library_v2/common/mavlink_msg_cellular_status.h \
    c_library_v2/common/mavlink_msg_change_operator_control.h \
    c_library_v2/common/mavlink_msg_change_operator_control_ack.h \
    c_library_v2/common/mavlink_msg_collision.h \
    c_library_v2/common/mavlink_msg_command_ack.h \
    c_library_v2/common/mavlink_msg_command_int.h \
    c_library_v2/common/mavlink_msg_command_long.h \
    c_library_v2/common/mavlink_msg_control_system_state.h \
    c_library_v2/common/mavlink_msg_data_stream.h \
    c_library_v2/common/mavlink_msg_data_transmission_handshake.h \
    c_library_v2/common/mavlink_msg_debug.h \
    c_library_v2/common/mavlink_msg_debug_float_array.h \
    c_library_v2/common/mavlink_msg_debug_vect.h \
    c_library_v2/common/mavlink_msg_distance_sensor.h \
    c_library_v2/common/mavlink_msg_encapsulated_data.h \
    c_library_v2/common/mavlink_msg_estimator_status.h \
    c_library_v2/common/mavlink_msg_extended_sys_state.h \
    c_library_v2/common/mavlink_msg_fence_status.h \
    c_library_v2/common/mavlink_msg_file_transfer_protocol.h \
    c_library_v2/common/mavlink_msg_flight_information.h \
    c_library_v2/common/mavlink_msg_follow_target.h \
    c_library_v2/common/mavlink_msg_global_position_int.h \
    c_library_v2/common/mavlink_msg_global_position_int_cov.h \
    c_library_v2/common/mavlink_msg_global_vision_position_estimate.h \
    c_library_v2/common/mavlink_msg_gps_global_origin.h \
    c_library_v2/common/mavlink_msg_gps_inject_data.h \
    c_library_v2/common/mavlink_msg_gps_input.h \
    c_library_v2/common/mavlink_msg_gps_raw_int.h \
    c_library_v2/common/mavlink_msg_gps_rtcm_data.h \
    c_library_v2/common/mavlink_msg_gps_rtk.h \
    c_library_v2/common/mavlink_msg_gps_status.h \
    c_library_v2/common/mavlink_msg_gps2_raw.h \
    c_library_v2/common/mavlink_msg_gps2_rtk.h \
    c_library_v2/common/mavlink_msg_heartbeat.h \
    c_library_v2/common/mavlink_msg_high_latency.h \
    c_library_v2/common/mavlink_msg_high_latency2.h \
    c_library_v2/common/mavlink_msg_highres_imu.h \
    c_library_v2/common/mavlink_msg_hil_actuator_controls.h \
    c_library_v2/common/mavlink_msg_hil_controls.h \
    c_library_v2/common/mavlink_msg_hil_gps.h \
    c_library_v2/common/mavlink_msg_hil_optical_flow.h \
    c_library_v2/common/mavlink_msg_hil_rc_inputs_raw.h \
    c_library_v2/common/mavlink_msg_hil_sensor.h \
    c_library_v2/common/mavlink_msg_hil_state.h \
    c_library_v2/common/mavlink_msg_hil_state_quaternion.h \
    c_library_v2/common/mavlink_msg_home_position.h \
    c_library_v2/common/mavlink_msg_isbd_link_status.h \
    c_library_v2/common/mavlink_msg_landing_target.h \
    c_library_v2/common/mavlink_msg_link_node_status.h \
    c_library_v2/common/mavlink_msg_local_position_ned.h \
    c_library_v2/common/mavlink_msg_local_position_ned_cov.h \
    c_library_v2/common/mavlink_msg_local_position_ned_system_global_offset.h \
    c_library_v2/common/mavlink_msg_log_data.h \
    c_library_v2/common/mavlink_msg_log_entry.h \
    c_library_v2/common/mavlink_msg_log_erase.h \
    c_library_v2/common/mavlink_msg_log_request_data.h \
    c_library_v2/common/mavlink_msg_log_request_end.h \
    c_library_v2/common/mavlink_msg_log_request_list.h \
    c_library_v2/common/mavlink_msg_logging_ack.h \
    c_library_v2/common/mavlink_msg_logging_data.h \
    c_library_v2/common/mavlink_msg_logging_data_acked.h \
    c_library_v2/common/mavlink_msg_manual_control.h \
    c_library_v2/common/mavlink_msg_manual_setpoint.h \
    c_library_v2/common/mavlink_msg_memory_vect.h \
    c_library_v2/common/mavlink_msg_message_interval.h \
    c_library_v2/common/mavlink_msg_mission_ack.h \
    c_library_v2/common/mavlink_msg_mission_changed.h \
    c_library_v2/common/mavlink_msg_mission_clear_all.h \
    c_library_v2/common/mavlink_msg_mission_count.h \
    c_library_v2/common/mavlink_msg_mission_current.h \
    c_library_v2/common/mavlink_msg_mission_item.h \
    c_library_v2/common/mavlink_msg_mission_item_int.h \
    c_library_v2/common/mavlink_msg_mission_item_reached.h \
    c_library_v2/common/mavlink_msg_mission_request.h \
    c_library_v2/common/mavlink_msg_mission_request_int.h \
    c_library_v2/common/mavlink_msg_mission_request_list.h \
    c_library_v2/common/mavlink_msg_mission_request_partial_list.h \
    c_library_v2/common/mavlink_msg_mission_set_current.h \
    c_library_v2/common/mavlink_msg_mission_write_partial_list.h \
    c_library_v2/common/mavlink_msg_mount_orientation.h \
    c_library_v2/common/mavlink_msg_named_value_float.h \
    c_library_v2/common/mavlink_msg_named_value_int.h \
    c_library_v2/common/mavlink_msg_nav_controller_output.h \
    c_library_v2/common/mavlink_msg_obstacle_distance.h \
    c_library_v2/common/mavlink_msg_odometry.h \
    c_library_v2/common/mavlink_msg_onboard_computer_status.h \
    c_library_v2/common/mavlink_msg_open_drone_id_authentication.h \
    c_library_v2/common/mavlink_msg_open_drone_id_basic_id.h \
    c_library_v2/common/mavlink_msg_open_drone_id_location.h \
    c_library_v2/common/mavlink_msg_open_drone_id_selfid.h \
    c_library_v2/common/mavlink_msg_open_drone_id_system.h \
    c_library_v2/common/mavlink_msg_optical_flow.h \
    c_library_v2/common/mavlink_msg_optical_flow_rad.h \
    c_library_v2/common/mavlink_msg_orbit_execution_status.h \
    c_library_v2/common/mavlink_msg_param_ext_ack.h \
    c_library_v2/common/mavlink_msg_param_ext_request_list.h \
    c_library_v2/common/mavlink_msg_param_ext_request_read.h \
    c_library_v2/common/mavlink_msg_param_ext_set.h \
    c_library_v2/common/mavlink_msg_param_ext_value.h \
    c_library_v2/common/mavlink_msg_param_map_rc.h \
    c_library_v2/common/mavlink_msg_param_request_list.h \
    c_library_v2/common/mavlink_msg_param_request_read.h \
    c_library_v2/common/mavlink_msg_param_set.h \
    c_library_v2/common/mavlink_msg_param_value.h \
    c_library_v2/common/mavlink_msg_ping.h \
    c_library_v2/common/mavlink_msg_play_tune.h \
    c_library_v2/common/mavlink_msg_position_target_global_int.h \
    c_library_v2/common/mavlink_msg_position_target_local_ned.h \
    c_library_v2/common/mavlink_msg_power_status.h \
    c_library_v2/common/mavlink_msg_protocol_version.h \
    c_library_v2/common/mavlink_msg_radio_status.h \
    c_library_v2/common/mavlink_msg_raw_imu.h \
    c_library_v2/common/mavlink_msg_raw_pressure.h \
    c_library_v2/common/mavlink_msg_rc_channels.h \
    c_library_v2/common/mavlink_msg_rc_channels_override.h \
    c_library_v2/common/mavlink_msg_rc_channels_raw.h \
    c_library_v2/common/mavlink_msg_rc_channels_scaled.h \
    c_library_v2/common/mavlink_msg_request_data_stream.h \
    c_library_v2/common/mavlink_msg_resource_request.h \
    c_library_v2/common/mavlink_msg_safety_allowed_area.h \
    c_library_v2/common/mavlink_msg_safety_set_allowed_area.h \
    c_library_v2/common/mavlink_msg_scaled_imu.h \
    c_library_v2/common/mavlink_msg_scaled_imu2.h \
    c_library_v2/common/mavlink_msg_scaled_imu3.h \
    c_library_v2/common/mavlink_msg_scaled_pressure.h \
    c_library_v2/common/mavlink_msg_scaled_pressure2.h \
    c_library_v2/common/mavlink_msg_scaled_pressure3.h \
    c_library_v2/common/mavlink_msg_serial_control.h \
    c_library_v2/common/mavlink_msg_servo_output_raw.h \
    c_library_v2/common/mavlink_msg_set_actuator_control_target.h \
    c_library_v2/common/mavlink_msg_set_attitude_target.h \
    c_library_v2/common/mavlink_msg_set_gps_global_origin.h \
    c_library_v2/common/mavlink_msg_set_home_position.h \
    c_library_v2/common/mavlink_msg_set_mode.h \
    c_library_v2/common/mavlink_msg_set_position_target_global_int.h \
    c_library_v2/common/mavlink_msg_set_position_target_local_ned.h \
    c_library_v2/common/mavlink_msg_setup_signing.h \
    c_library_v2/common/mavlink_msg_sim_state.h \
    c_library_v2/common/mavlink_msg_smart_battery_info.h \
    c_library_v2/common/mavlink_msg_smart_battery_status.h \
    c_library_v2/common/mavlink_msg_statustext.h \
    c_library_v2/common/mavlink_msg_statustext_long.h \
    c_library_v2/common/mavlink_msg_storage_information.h \
    c_library_v2/common/mavlink_msg_sys_status.h \
    c_library_v2/common/mavlink_msg_system_time.h \
    c_library_v2/common/mavlink_msg_terrain_check.h \
    c_library_v2/common/mavlink_msg_terrain_data.h \
    c_library_v2/common/mavlink_msg_terrain_report.h \
    c_library_v2/common/mavlink_msg_terrain_request.h \
    c_library_v2/common/mavlink_msg_time_estimate_to_target.h \
    c_library_v2/common/mavlink_msg_timesync.h \
    c_library_v2/common/mavlink_msg_trajectory_representation_bezier.h \
    c_library_v2/common/mavlink_msg_trajectory_representation_waypoints.h \
    c_library_v2/common/mavlink_msg_tunnel.h \
    c_library_v2/common/mavlink_msg_uavcan_node_info.h \
    c_library_v2/common/mavlink_msg_uavcan_node_status.h \
    c_library_v2/common/mavlink_msg_utm_global_position.h \
    c_library_v2/common/mavlink_msg_v2_extension.h \
    c_library_v2/common/mavlink_msg_vfr_hud.h \
    c_library_v2/common/mavlink_msg_vibration.h \
    c_library_v2/common/mavlink_msg_vicon_position_estimate.h \
    c_library_v2/common/mavlink_msg_video_stream_information.h \
    c_library_v2/common/mavlink_msg_video_stream_status.h \
    c_library_v2/common/mavlink_msg_vision_position_estimate.h \
    c_library_v2/common/mavlink_msg_vision_speed_estimate.h \
    c_library_v2/common/mavlink_msg_wheel_distance.h \
    c_library_v2/common/mavlink_msg_wifi_config_ap.h \
    c_library_v2/common/mavlink_msg_wind_cov.h \
    c_library_v2/common/testsuite.h \
    c_library_v2/common/version.h \
    c_library_v2/icarous/icarous.h \
    c_library_v2/icarous/mavlink.h \
    c_library_v2/icarous/mavlink_msg_icarous_heartbeat.h \
    c_library_v2/icarous/mavlink_msg_icarous_kinematic_bands.h \
    c_library_v2/icarous/testsuite.h \
    c_library_v2/icarous/version.h \
    c_library_v2/matrixpilot/matrixpilot.h \
    c_library_v2/matrixpilot/mavlink.h \
    c_library_v2/matrixpilot/mavlink_msg_airspeeds.h \
    c_library_v2/matrixpilot/mavlink_msg_altitudes.h \
    c_library_v2/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    c_library_v2/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    c_library_v2/matrixpilot/mavlink_msg_flexifunction_command.h \
    c_library_v2/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    c_library_v2/matrixpilot/mavlink_msg_flexifunction_directory.h \
    c_library_v2/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    c_library_v2/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    c_library_v2/matrixpilot/mavlink_msg_flexifunction_set.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f17.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f18.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f19.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f20.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f21.h \
    c_library_v2/matrixpilot/mavlink_msg_serial_udb_extra_f22.h \
    c_library_v2/matrixpilot/testsuite.h \
    c_library_v2/matrixpilot/version.h \
    c_library_v2/minimal/mavlink.h \
    c_library_v2/minimal/mavlink_msg_heartbeat.h \
    c_library_v2/minimal/mavlink_msg_protocol_version.h \
    c_library_v2/minimal/minimal.h \
    c_library_v2/minimal/testsuite.h \
    c_library_v2/minimal/version.h \
    c_library_v2/slugs/mavlink.h \
    c_library_v2/slugs/mavlink_msg_boot.h \
    c_library_v2/slugs/mavlink_msg_control_surface.h \
    c_library_v2/slugs/mavlink_msg_cpu_load.h \
    c_library_v2/slugs/mavlink_msg_ctrl_srfc_pt.h \
    c_library_v2/slugs/mavlink_msg_data_log.h \
    c_library_v2/slugs/mavlink_msg_diagnostic.h \
    c_library_v2/slugs/mavlink_msg_gps_date_time.h \
    c_library_v2/slugs/mavlink_msg_isr_location.h \
    c_library_v2/slugs/mavlink_msg_mid_lvl_cmds.h \
    c_library_v2/slugs/mavlink_msg_novatel_diag.h \
    c_library_v2/slugs/mavlink_msg_ptz_status.h \
    c_library_v2/slugs/mavlink_msg_sensor_bias.h \
    c_library_v2/slugs/mavlink_msg_sensor_diag.h \
    c_library_v2/slugs/mavlink_msg_slugs_camera_order.h \
    c_library_v2/slugs/mavlink_msg_slugs_configuration_camera.h \
    c_library_v2/slugs/mavlink_msg_slugs_mobile_location.h \
    c_library_v2/slugs/mavlink_msg_slugs_navigation.h \
    c_library_v2/slugs/mavlink_msg_status_gps.h \
    c_library_v2/slugs/mavlink_msg_uav_status.h \
    c_library_v2/slugs/mavlink_msg_volt_sensor.h \
    c_library_v2/slugs/slugs.h \
    c_library_v2/slugs/testsuite.h \
    c_library_v2/slugs/version.h \
    c_library_v2/standard/mavlink.h \
    c_library_v2/standard/standard.h \
    c_library_v2/standard/testsuite.h \
    c_library_v2/standard/version.h \
    c_library_v2/test/mavlink.h \
    c_library_v2/test/mavlink_msg_test_types.h \
    c_library_v2/test/test.h \
    c_library_v2/test/testsuite.h \
    c_library_v2/test/version.h \
    c_library_v2/uAvionix/mavlink.h \
    c_library_v2/uAvionix/mavlink_msg_uavionix_adsb_out_cfg.h \
    c_library_v2/uAvionix/mavlink_msg_uavionix_adsb_out_dynamic.h \
    c_library_v2/uAvionix/mavlink_msg_uavionix_adsb_transceiver_health_report.h \
    c_library_v2/uAvionix/testsuite.h \
    c_library_v2/uAvionix/uAvionix.h \
    c_library_v2/uAvionix/version.h

DISTFILES += \
    c_library_v2/message_definitions/ardupilotmega.xml \
    c_library_v2/message_definitions/ASLUAV.xml \
    c_library_v2/message_definitions/autoquad.xml \
    c_library_v2/message_definitions/common.xml \
    c_library_v2/message_definitions/icarous.xml \
    c_library_v2/message_definitions/matrixpilot.xml \
    c_library_v2/message_definitions/minimal.xml \
    c_library_v2/message_definitions/paparazzi.xml \
    c_library_v2/message_definitions/python_array_test.xml \
    c_library_v2/message_definitions/slugs.xml \
    c_library_v2/message_definitions/standard.xml \
    c_library_v2/message_definitions/test.xml \
    c_library_v2/message_definitions/ualberta.xml \
    c_library_v2/message_definitions/uAvionix.xml
